### ISSUE TITLE
OOC can crash the server

### ISSUE THREAD

**Issue by AlcaroIsAFrick** [AlcaroIsAFrick/Dab13#3]
self cpu goes over 5 sometimes, and total cpu is a fucking LOT

**Comment by LuigiBoi** [comment]
feature

**Comment by MACIEKBAKI** [comment]
agree

**Comment by AlcaroIsAFrick** [comment]
clients joining can also crash the server

**Comment by AlcaroIsAFrick** [comment]
WTF CODERFS HAVENT FIXDE IT!!!!!!!!

im not sure how to fix this because it's a DLL thing with the discord webhook
